projects:
  - name: gcp-project-id
    provider: gke
    clusters:
      - name: gke-cluster-name
        zone: zone # for zonal GKE clusters
        region: region # for regional GKE clusters
        context: name-to-be-used-for-this-context
        tmux_envs:
          ENV_VARIABLE: value
        provider_envs:
          ENV_VARIABLE: value
  - name: aws-project-id
    provider: eks
    clusters:
      - name: eks-cluster-name
        region: region
        context: name-to-be-used-for-this-context
        tmux_envs:
          AWS_PROFILE: profile-to-use-in-tmux
          ENV_VARIABLE: value
        provider_envs:
          AWS_PROFILE: profile-to-use-to-config-kubectl
          ENV_VARIABLE: value
